// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdFx9xNLfZiDm3uULw7RtNiBb0EVcmppA',
    appId: '1:330146928360:web:a56fd0bd8525c3328bdb5d',
    messagingSenderId: '330146928360',
    projectId: 'igit-connects',
    authDomain: 'igit-connects.firebaseapp.com',
    storageBucket: 'igit-connects.firebasestorage.app',
    measurementId: 'G-HYCL849NJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLlCpuhO-jv8D-4Kh6OKgh9sOX15_qI1g',
    appId: '1:330146928360:android:92054ea69181181d8bdb5d',
    messagingSenderId: '330146928360',
    projectId: 'igit-connects',
    storageBucket: 'igit-connects.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdFx9xNLfZiDm3uULw7RtNiBb0EVcmppA',
    appId: '1:330146928360:web:6c8a576ab5c06c518bdb5d',
    messagingSenderId: '330146928360',
    projectId: 'igit-connects',
    authDomain: 'igit-connects.firebaseapp.com',
    storageBucket: 'igit-connects.firebasestorage.app',
    measurementId: 'G-1QFTRM8EFH',
  );

}